### ISSUE TITLE
Using together with Page Forms

### ISSUE THREAD

**Issue by kaddigat** [edwardspec/mediawiki-moderation#34]
Is it possible to use Page Forms for "continue editing" a page after having an edit sent to moderation?

In detail:
I use Page forms for my wiki to make it easier for users. If they edit the page, the edit is sent to moderation and they get this message

> Pending review
> 
> Success: your edit has been sent to moderation.
> You can continue editing your version of this page.

with a link to continue editing the page (....&action=edit). At the moment they see the plain text of the page when they continue editing. In order to make it easier for them, could you change the link to  (....&action=formedit) sothat they can use the Page Form for further edits? 

Of course this would only make sense as an additional option for peole who use Page Forms.

**Comment by edwardspec** [comment]
Could you please check if the pending change is shown when its author opens &action=formedit?
(i.e. is changing the link enough?)

**Comment by kaddigat** [comment]
You are right. The pending change is not shown if the author opens &action=formedit
Unfortunately changing the link seems not to solve the problem.

**Comment by edwardspec** [comment]
I'll have a look at PageForms extension to see if we can inject the pending change into the form.

**Comment by edwardspec** [comment]
Only partially possible without dirty code.
There are two situations:
1) non-automoderated user creates a new page (e.g. "Bengal" using "Form:Cat"), and then continues editing "Bengal" via formedit.
In this situation, the pending change can be displayed easily:
```php
$wgHooks['PageForms::EditFormPreloadText'] = function( &$preloadContent, $targetTitle, $formTitle ) {
	ModerationPreload::onEditFormPreloadText( $preloadContent, $targetTitle );
	return true;
}
```
2) However, when the page Bengal already exists in the wiki (was created before), Extension:PageForms doesn't call above-mentioned hook. Thus we can't provide the pending text to PageForms.

I'll send a pull request to developers of Extension:PageForms to add analogue of hook `EditFormInitialText`, which handles situation (2) in normal action=edit.

**Comment by edwardspec** [comment]
Submitted a change to Extension:PageForms:
https://gerrit.wikimedia.org/r/420950 - Add analogue of EditFormInitialText hook from MediaWiki core

If they approve it,  it will be easy to handle the rest on Moderation side.

**Comment by edwardspec** [comment]
Implemented in 1.1.24.
Please confirm that it works for you.

Note that https://gerrit.wikimedia.org/r/#/c/420950/ has not yet been merged into Extension:PageForms, so you might have to apply it manually.

**Comment by edwardspec** [comment]
Above-mentioned change has been merged into PageForms.

In the latest versions of Moderation and PageForms, Special:EditForm now works as expected.
Closing as resolved.

**Comment by kaddigat** [comment]
Thanks for the quick implementation. In General it works fine.
Unfortunately I get an Fatal exception of type "Error" when using a direct link to PageForms as described under "The one step process" here. https://www.mediawiki.org/wiki/Extension:Page_Forms/Linking_to_forms. As I don't know whether this problem is related to PageForms, or to Moderation extension, I posted it here.
Without the recent changes everything worked fine.

[WsUQHn8AAQEAAMJ0mH0AAABE] /Special:FormEdit/FileUpload Error from line 174 of /data/web/e78800/html/apps/mediawiki-59399/extensions/Moderation/hooks/ModerationPreload.php: Call to a member function getNamespace() on null

Backtrace:

#0 /data/web/e78800/html/apps/mediawiki-59399/extensions/Moderation/hooks/ModerationPreload.php(208): ModerationPreload->loadUnmoderatedEdit(NULL)
#1 /data/web/e78800/html/apps/mediawiki-59399/extensions/Moderation/hooks/ModerationPreload.php(248): ModerationPreload::showUnmoderatedEdit(string, NULL, NULL)
#2 /data/web/e78800/html/apps/mediawiki-59399/extensions/Moderation/plugins/ModerationPageForms.php(33): ModerationPreload::onEditFormPreloadText(string, NULL)
#3 /data/web/e78800/html/apps/mediawiki-59399/includes/Hooks.php(186): ModerationPageForms::preloadText(string, NULL, Title)
#4 /data/web/e78800/html/apps/mediawiki-59399/extensions/PageForms/includes/PF_AutoeditAPI.php(848): Hooks::run(string, array)
#5 /data/web/e78800/html/apps/mediawiki-59399/extensions/PageForms/includes/PF_AutoeditAPI.php(111): PFAutoeditAPI->doAction()
#6 /data/web/e78800/html/apps/mediawiki-59399/extensions/PageForms/specials/PF_FormEdit.php(96): PFAutoeditAPI->execute()
#7 /data/web/e78800/html/apps/mediawiki-59399/extensions/PageForms/specials/PF_FormEdit.php(43): PFFormEdit->printForm(string, string, NULL)
#8 /data/web/e78800/html/apps/mediawiki-59399/includes/specialpage/SpecialPage.php(522): PFFormEdit->execute(string)
#9 /data/web/e78800/html/apps/mediawiki-59399/includes/specialpage/SpecialPageFactory.php(578): SpecialPage->run(string)
#10 /data/web/e78800/html/apps/mediawiki-59399/includes/MediaWiki.php(287): SpecialPageFactory::executePath(Title, RequestContext)
#11 /data/web/e78800/html/apps/mediawiki-59399/includes/MediaWiki.php(862): MediaWiki->performRequest()
#12 /data/web/e78800/html/apps/mediawiki-59399/includes/MediaWiki.php(523): MediaWiki->main()
#13 /data/web/e78800/html/apps/mediawiki-59399/index.php(43): MediaWiki->run()
#14 {main}

**Comment by kaddigat** [comment]
Another small thing (independent of the above mentioned error):

Is there a simple way to change the link the user sees after commiting some changes from 
&action=edit to &action=formedit?

> Pending review
> 
> Success: your edit has been sent to moderation.
> You can continue editing your version of this page.

**Comment by edwardspec** [comment]
Investigating.

> Is there a simple way to change the link the user sees after commiting some changes from
&action=edit to &action=formedit?

It already should point to Special:FormEdit if the user edited the page via Special:FormEdit.

**Comment by edwardspec** [comment]
The exception should be fixed in 1.1.25.

**Comment by kaddigat** [comment]
Works for me. Thanks.

About the [continue editing ...] link:

> I thought I did it already,
> the link [continue editing ...] should point to Special:FormEdit if the user edited the page via Special:FormEdit.

It does if you use the Special:FormEdit/Formname/Pagename. However it is more common to use this possibility https://www.mediawiki.org/wiki/Extension:Page_Forms/The_%22edit_with_form%22_tab which comes out with the link: _...PAGENAME&action=formedit_
Unfortunately it does not work for this method.

**Comment by edwardspec** [comment]
Implemented in 1.1.26.
If user edited via action=formedit, [continue editing ...] link will point to action=formedit.

**Comment by kaddigat** [comment]
Works for me. Thank you!!!
