### ISSUE TITLE
Error running update.php after install

### ISSUE THREAD

**Issue by FilmGood** [edwardspec/mediawiki-moderation#51]
Hi, I'm trying to install this extension to my wiki. I've previously updated this wiki from an older version. It seems to also crash the site if I simply enable the extension in LocalSettings.php. Running update.php gives me this error, and the site continues to crash until I remove the extension from LocalSettings.php

I hope this is detailed enough that a problem can be identified.

Thanks,
FilmGood
```
Applying /var/www/FilmWiki/public/extensions/Moderation/hooks/../sql/patch-make-preload-unique.sql patch ...[2966bd7c42846c3da6e01f85] [no req]   Wikimedia\Rdbms\DBQueryError from line 1587 of /var/www/FilmWiki/public/includes/libs/rdbms/database/Database.php: A database query error has occurred. Did you forget to run your application's database schema updater after upgrading?
Query: DROP INDEX moderation_load ON `fw_moderation`

Function: Wikimedia\Rdbms\Database::sourceFile( /var/www/FilmWiki/public/extensions/Moderation/hooks/../sql/patch-make-preload-unique.sql )
Error: 1091 Can't DROP 'moderation_load'; check that column/key exists (localhost)

Backtrace:
#0 /var/www/FilmWiki/public/includes/libs/rdbms/database/Database.php(1556): Wikimedia\Rdbms\Database->getQueryExceptionAndLog(string, integer, string, string)
#1 /var/www/FilmWiki/public/includes/libs/rdbms/database/Database.php(1274): Wikimedia\Rdbms\Database->reportQueryError(string, integer, string, string, boolean)
#2 /var/www/FilmWiki/public/includes/libs/rdbms/database/Database.php(4430): Wikimedia\Rdbms\Database->query(string, string)
#3 /var/www/FilmWiki/public/includes/libs/rdbms/database/Database.php(4365): Wikimedia\Rdbms\Database->sourceStream(resource (closed), NULL, NULL, string, NULL)
#4 /var/www/FilmWiki/public/includes/installer/DatabaseUpdater.php(690): Wikimedia\Rdbms\Database->sourceFile(string)
#5 /var/www/FilmWiki/public/includes/installer/DatabaseUpdater.php(489): DatabaseUpdater->applyPatch(string, boolean)
#6 /var/www/FilmWiki/public/includes/installer/DatabaseUpdater.php(457): DatabaseUpdater->runUpdates(array, boolean)
#7 /var/www/FilmWiki/public/maintenance/update.php(203): DatabaseUpdater->doUpdates(array)
#8 /var/www/FilmWiki/public/maintenance/doMaintenance.php(96): UpdateMediaWiki->execute()
#9 /var/www/FilmWiki/public/maintenance/update.php(266): require_once(string)
#10 {main}
```

**Comment by edwardspec** [comment]
Will investigate.

As a quick workaround, please run the following SQL query:
```sql
CREATE UNIQUE INDEX moderation_load ON fw_moderation (mod_preloadable, mod_namespace, mod_title, mod_preload_id);
```
... and then run update.php again.

**Comment by FilmGood** [comment]
Thank you for the fast reply. When I try running that query I get the following error:
```sql
ERROR 1071 (42000): Specified key was too long; max key length is 767 bytes
```
I tried googling what it means but  I'm at a loss.

**Comment by edwardspec** [comment]
I know that error. It's caused when $wgDBTableOptions setting (in your LocalSettings.php) mentions charsets other than binary.
Please try the following (it's the default for modern versions of MediaWiki):
```php
$wgDBTableOptions = 'ENGINE=InnoDB, DEFAULT CHARSET=binary';
``

**Comment by FilmGood** [comment]
Changing that setting doesn't seem to affect anything. I tried running `update.php` afterwards as well. You were right that it was set to UTF-8 however.

**Comment by edwardspec** [comment]
This setting only affects new tables. Please try the following:
```
ALTER TABLE fw_moderation CONVERT TO CHARACTER SET binary;
```

**Comment by FilmGood** [comment]
Awesome! Well that got us further :)
Doesn't seem to be any errors when running `update.php` anymore, but the site still crashes with this error:
```
Query: SELECT mod_timestamp FROM `fw_moderation` FORCE INDEX (moderation_folder_pending) WHERE mod_rejected = '0' AND mod_merged_revid = '0' LIMIT 1
Function: ModerationNotifyModerator::getPendingTimeUncached
Error: 1176 Key 'moderation_folder_pending' doesn't exist in table 'fw_moderation' (localhost)
```

**Comment by edwardspec** [comment]
Please show me the output of the following SQL command:
```sql
SHOW INDEX IN moderation;
```

**Comment by FilmGood** [comment]
Doesn't look good lol
```
ERROR 1146 (42S02): Table 'filmwiki.moderation' doesn't exist
```

**Comment by edwardspec** [comment]
Sorry, I missed the "fw_" prefix. The command is
`SHOW INDEX IN fw_moderation;`

**Comment by FilmGood** [comment]
```
+---------------+------------+-----------------+--------------+-----------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| Table         | Non_unique | Key_name        | Seq_in_index | Column_name     | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment |
+---------------+------------+-----------------+--------------+-----------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| fw_moderation |          0 | PRIMARY         |            1 | mod_id          | A         |           0 |     NULL | NULL   |      | BTREE      |         |               |
| fw_moderation |          0 | moderation_load |            1 | mod_preloadable | A         |           0 |     NULL | NULL   |      | BTREE      |         |               |
| fw_moderation |          0 | moderation_load |            2 | mod_namespace   | A         |           0 |     NULL | NULL   |      | BTREE      |         |               |
| fw_moderation |          0 | moderation_load |            3 | mod_title       | A         |           0 |     NULL | NULL   |      | BTREE      |         |               |
| fw_moderation |          0 | moderation_load |            4 | mod_preload_id  | A         |           0 |     NULL | NULL   |      | BTREE      |         |               |
+---------------+------------+-----------------+--------------+-----------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
5 rows in set (0.01 sec)
```

**Comment by edwardspec** [comment]
Thought so.
All the indexes are missing for whatever reason. (and it's not a bug in the extension - these indexes existed from version 0.0.1)

Need to fix this manually. Please try the following:
```sql
DROP INDEX moderation_load on fw_moderation;
CREATE UNIQUE INDEX moderation_load ON fw_moderation (mod_preloadable, mod_type, mod_namespace, mod_title, mod_preload_id);
CREATE INDEX moderation_approveall ON fw_moderation (mod_user_text, mod_rejected, mod_conflict);
CREATE INDEX moderation_rejectall ON fw_moderation (mod_user_text, mod_rejected, mod_merged_revid);
CREATE INDEX moderation_folder_pending ON fw_moderation (mod_rejected, mod_merged_revid, mod_timestamp);
CREATE INDEX moderation_folder_rejected ON fw_moderation (mod_rejected, mod_rejected_auto, mod_merged_revid, mod_timestamp);
CREATE INDEX moderation_folder_merged ON fw_moderation (mod_merged_revid, mod_timestamp);
CREATE INDEX moderation_folder_spam ON fw_moderation (mod_rejected_auto, mod_timestamp);
CREATE INDEX moderation_signup ON fw_moderation (mod_preload_id, mod_preloadable);
```

**Comment by FilmGood** [comment]
Thanks, it's all working now! I appreciate the time you took for me.
