### ISSUE TITLE
InvalidArgumentException when attempting to edit from Special:Moderation (Conflict with MsUpload?)

### ISSUE THREAD

**Issue by Reception123** [edwardspec/mediawiki-moderation#69]
**List of steps to reproduce** (step by step, including full links if applicable):
* Install and enable Moderation 
* Visit Special:Moderation
* Click on the 'edit' button next to any page that is to be moderated (see {F35072980})

**What happens?**:

```
from /srv/mediawiki/w/includes/page/WikiPageFactory.php(60)
#0 /srv/mediawiki/w/extensions/MsUpload/includes/Hooks.php(25): MediaWiki\Page\WikiPageFactory->newFromTitle(Title)
#1 /srv/mediawiki/w/includes/HookContainer/HookContainer.php(338): MsUpload\Hooks::onEditPageShowEditFormInitial(ModerationEditChangePage, OutputPage)
#2 /srv/mediawiki/w/includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook(string, array, array, array)
#3 /srv/mediawiki/w/includes/HookContainer/HookRunner.php(1599): MediaWiki\HookContainer\HookContainer->run(string, array)
#4 /srv/mediawiki/w/includes/EditPage.php(2900): MediaWiki\HookContainer\HookRunner->onEditPage__showEditForm_initial(ModerationEditChangePage, OutputPage)
#5 /srv/mediawiki/w/extensions/Moderation/action/review/ModerationActionEditChange.php(71): EditPage->showEditForm()
#6 /srv/mediawiki/w/extensions/Moderation/SpecialModeration.php(213): ModerationActionEditChange->outputResult(array, OutputPage)
#7 /srv/mediawiki/w/extensions/Moderation/SpecialModeration.php(168): SpecialModeration->runModerationAction()
#8 /srv/mediawiki/w/includes/specialpage/SpecialPage.php(647): SpecialModeration->execute(NULL)
#9 /srv/mediawiki/w/includes/specialpage/SpecialPageFactory.php(1366): SpecialPage->run(NULL)
#10 /srv/mediawiki/w/includes/MediaWiki.php(314): MediaWiki\SpecialPage\SpecialPageFactory->executePath(string, RequestContext)
#11 /srv/mediawiki/w/includes/MediaWiki.php(930): MediaWiki->performRequest()
#12 /srv/mediawiki/w/includes/MediaWiki.php(564): MediaWiki->main()
#13 /srv/mediawiki/w/index.php(53): MediaWiki->run()
#14 /srv/mediawiki/w/index.php(46): wfIndexMain()
#15 {main}
```

**What should have happened instead?**:
It should have been possible to edit that page

**Software version (if not a Wikimedia wiki), browser information, screenshots, other information, etc.**:

```
MediaWiki 1.37.2 (1075d4b)
21:34, 28 April 2022
PHP 7.4.28 (fpm-fcgi)
MariaDB 10.5.15-MariaDB-1:10.5.15+maria~bullseye-log
```

original downstream: https://phabricator.miraheze.org/T9144

Note: Sorr

**Comment by edwardspec** [comment]
1) Not reproduced without Extension:MsUpload.
2) Problem is in Extension:MsUpload, which currently doesn't work with any special pages that invoke EditPage (not just Special:Moderation).
3) Details on issue in MsUpload (in `includes/Hooks.php`, `Hooks::onEditPageShowEditFormInitial`): it assumes that OutputPage::getTitle() always returns a title of an editable page, and it tries to create a WikiPage object from it. This fails, because "Special:Moderation" is not a valid title for a WikiPage.
4) While I can theoretically workaround this in Moderation by setting OutputPage::getTitle() to return something else, it would be a dirty hack that might cause other problems, so it would be optimal if this was fixed in MsUpload.
